### ISSUE TITLE
Home: Create Sequence dialog should be named 'Create Sequence' not 'Name'

### ISSUE THREAD

**Issue by craftjk** [TeselaGen/das#107]
_From @mfero on September 24, 2015 19:36_

Starting from My Sequences + button or from Home: Create Sequence button, modal window should be same as route taken if you hit the My Sequences + button. Why short-circuit the new dialog? When you do get to the naming window... the window name should not be "Name" but should reflect what link rasied the window... so "Create Sequence" or "Create New Blank Sequence" should be used instead of "Name". "Name" is more appropriate as a field name not a window name.

_Copied from original issue: TeselaGen/ve#1387_

**Comment by mfero** [comment]
looks good. Home: Create Sequence button has been removed - thanks! it did not belong.

**Comment by njhillson** [comment]
Seems to be fine.
