### ISSUE TITLE
New Project modal window should be "New Project" not "Name"

### ISSUE THREAD

**Issue by craftjk** [TeselaGen/das#108]
_From @mfero on September 24, 2015 19:30_

Starting from either the home page or using the new project button... New Project modal window should be "New Project" not "Name"

_Copied from original issue: TeselaGen/ve#1386_

**Comment by craftjk** [comment]
_From @mfero on October 26, 2015 5:22_

Not seeing on dow.teselagen.com

**Comment by mfero** [comment]
Another ticket that is appearing twice on waffle. Declaring victory and closing to clean up board.
