### ISSUE TITLE
Make sure we can get LDAP authentication working

### ISSUE THREAD

**Issue by craftjk** [TeselaGen/das#109]
_From @craftjk on August 26, 2015 20:44_

It's what DAS is using

_Copied from original issue: TeselaGen/ve#1314_

**Comment by craftjk** [comment]
_From @rpavez on October 20, 2015 11:31_

Should be working now, test with mike@ldap.teselagen.com password Te#rocks
We tested LDAP with DOW config last week and it worked.

**Comment by craftjk** [comment]
_From @mfero on October 27, 2015 3:44_

We need a way to test this. Can we emulate the Dow setup on our server?

![image](https://cloud.githubusercontent.com/assets/7561861/10748952/591953f0-7c22-11e5-86d0-6260f0e14322.png)

**Comment by craftjk** [comment]
_From @rpavez on October 30, 2015 18:29_

Doesn't look like you were testing in dowdev.teselagen.com, this is only available in dow and dowdev and you should select Connection Type ActiveDirectory.
![screen shot 2015-10-30 at 3 27 03 pm](https://cloud.githubusercontent.com/assets/555910/10854496/d627ad74-7f1a-11e5-895d-f2267ae1d971.png)

**Comment by craftjk** [comment]
_From @mfero on October 30, 2015 18:29_

ok, i’ll retest...

**Comment by mfero** [comment]
not sure how to test since our interface is not what DAS is using. moving along.

**Comment by njhillson** [comment]
username:
mike@ldap.teselagen.com
password:
Te#rocks
Connection Type:
ActiveDirectory
Server:
http://dowdev.teselagen.com/
is not working for me. Failing.

**Comment by mfero** [comment]
rodrigo, this ticket is resolved at DAS no?

**Comment by rpavez** [comment]
This ticket is resolved for DAS and now also for us. Please test again.
