### ISSUE TITLE
Task Monitor stuck on loading mask, loading mask persists after minimizing Task Monitor

### ISSUE THREAD

**Issue by craftjk** [TeselaGen/das#113]
After submitting a j5run, the loading mask over the Task Monitor never goes away.   If you click the collapse button on the panel, the panel collapses but the loading mask persists.

![screen shot 2015-11-09 at 10 11 36 am](https://cloud.githubusercontent.com/assets/4167907/11042169/776e062c-86ca-11e5-961e-5b35b9120b19.png)

![screen shot 2015-11-09 at 10 11 53 am](https://cloud.githubusercontent.com/assets/4167907/11042166/7387011c-86ca-11e5-9e2d-4b895bb303ad.png)

**Comment by mfero** [comment]
j5 and taskmonitor working now on dowdev.

**Comment by njhillson** [comment]
Not seeing this issue now.
