### ISSUE TITLE
Same sequence can be copied to Peony Repo multiple times (DAS#12)

### ISSUE THREAD

**Issue by mcfa77y** [TeselaGen/das#115]
das issue 12

**Comment by mfero** [comment]
Same sequence could not be copied into shared repo. thank goodness.

**Comment by njhillson** [comment]
Looks good.

**Comment by mfero** [comment]
Adam Q: 12 - This issue states, "Same sequence can be copied to Peony Repo multiple times" This issue appears to be tied to the idea of validating sequences going into the shared repo. We hash the sequences. Would it be sufficient to compare the hash and not allow duplicate hashes in the sequence tables? Additionally do we need to prevent duplicate sequence names?

Sandra A: (missing)
