### ISSUE TITLE
Standardize DOW LDAP Auth case sensitivity

### ISSUE THREAD

**Issue by rpavez** [TeselaGen/das#117]
We need to standardize LDAP to either uppercase or lower case, and check it works for Dow. One test would be create an LDAP user like rpavez@ldap.teselagen and RPAVEZ@ldap.teselagen.com and make suer only one user is created.

**Comment by mfero** [comment]
I created two users, MIKEEFERO and mikeefero. They seem to be treated as distinct users indicating case-sensitivity of user name. Seems right to me. Need to check with DAS to see if this is the expected behavior.
