### ISSUE TITLE
can't create part from sequence features via context menu

### ISSUE THREAD

**Issue by mcfa77y** [TeselaGen/das#118]

**Comment by mfero** [comment]
Is this the same as (DAS#17) TeselaGen/das#125 ? If so it looks like it is already working on dowdev.

**Comment by mfero** [comment]
OK, I jumped the gun... sort of working but not quite. I'll put this back where I found it and talk to Joe.

**Comment by mfero** [comment]
Seems to be working nicely now.

**Comment by njhillson** [comment]
Looks good.
