### ISSUE TITLE
Error importing amino acid files (DAS #10)

### ISSUE THREAD

**Issue by mfero** [TeselaGen/das#122]
This may have been fixed in the context of another ticket. Requires QA.

**Comment by mfero** [comment]
Fasta protein sequence upload works.
Genbank protein sequence works.
Note: only viewer is simple text box, no annotation is viewable.

**Comment by njhillson** [comment]
I was able to import a protein FASTA format file (including multiple entry), but unable to import a GenPept protein sequence file.
Download as a test case for example:
http://www.ncbi.nlm.nih.gov/protein/NP_003623.1?report=gpwithparts&log$=seqview
I do not know the requirements, but based on what Mike seemed to suggest, GenPept is required?
Failing, but please correct my understanding of requirements...

**Comment by mfero** [comment]
Lets check with team to see what is implemented now, and with DAS on what we think we need for 90-day milestone. There are a large number of formats and edge cases we still need to take care of, but not for 90-Day. (90-day is primarily an exercise in re-write existing routes for Oracle plus other enterprise enhancements).
