### ISSUE TITLE
Users attempting to route to a HTTP:// url of the app will be redirected to HTTPS://. In Chrome, the browser does not redirect to HTTPS. (DAS#23)

### ISSUE THREAD

**Issue by mfero** [TeselaGen/das#127]
Fixed? Requires QA

**Comment by mfero** [comment]
Seems to be working on dowdev. moving on.

**Comment by njhillson** [comment]
This is not working for me. If I go to
https://dowdev.teselagen.com
I get a "503 Service Unavailable No server is available to handle this request. " error message. Failing.

**Comment by mfero** [comment]
From DOW:
Tested on 12/3.  When I clear my browser cache, re-start browser, and place http://elc6ttes01:3443/ in my browser, Chrome spins and shows the attached screen shot. http1.png, http2.png

**Comment by mfero** [comment]
This is prob a  server configuration issue that Rodrigo and DAS will try to resolve today Dec 10. QA will come from the results of todays meeting.

**Comment by mfero** [comment]
This was fixed at today's meeting with DAS.
