### ISSUE TITLE
Users with the “viewer” role can query for data. (DAS#1)

### ISSUE THREAD

**Issue by mfero** [TeselaGen/das#131]
Fixed. Requires QA.

**Comment by mfero** [comment]
standard search seems to be working for viewer/editor.

**Comment by njhillson** [comment]
I don't think I understand what this ticket was asking for.  "Search" or really filtering, seems to work for viewer role in shared sequence repo. Passing...

**Comment by mfero** [comment]
Adam Q: 1 - One of the issues for issue #1 states, "Users with the “viewer” role can query for data." We aware of the issue that the viewer could not see the shared repo sequences in the initial release. Is the data this issue sequence and part data? Or is there other data the viewer role needs to be able to query? Or is there specific query options for the sequence and part data that wasn't available to use?

Sandra A: Users with viewer role should be able to see sequences and  parts in the shared repo to meet the milestone.  Please see the FAGTOPAccessControl.zip which demonstrates this.
