### ISSUE TITLE
Data is in the shared repo where “viewer” and “admin” users can see it (DAS#1)

### ISSUE THREAD

**Issue by mfero** [TeselaGen/das#133]

**Comment by mfero** [comment]
I can indeed see the shared data as a viewer, but only if I first copy to my local sandbox. An enhancement will be to allow viewing before copying.

**Comment by njhillson** [comment]
I am not sure what the desired behavior is. I can see shared parts and sequences as a viewer. However, I don't see a my sequences tab, so I don't see what Mike is talking about above. Passing...
