### ISSUE TITLE
“admin” users can grant row-level access privileges to items in the shared repo on a per user basis (DAS#4)

### ISSUE THREAD

**Issue by mfero** [TeselaGen/das#134]
Through admin>Access Control>(select a user and double-click)
I was able change a viewer's ability to display a row containing data that had the row level permission changed to "false".

**Comment by njhillson** [comment]
This ticket is very confusing in language. Not sure what the intention is. It wold be better to word these ticket titles in the negative or at like in the "should" sense. I assume this ticket title is the desired behavior. In any case passing...

**Comment by mfero** [comment]
Adam Q: 4 - This issue states "“admin” users can grant row-level access privileges to items in the shared repo on a per user basis". The app currently works by giving a user the viewer role so they can view all shared sequences and then if an admin chooses, they can "backlist" sequences per user at a row/record level to remove that user's privilege to see that sequence. Are we correct in understanding that you would like to grant users access to individual sequences in the shared repo even if the user doesn't have the viewer role?
Sandra A: No.  The admin user granted the VIEWER and EDITOR role to another user and that user couldn’t see any shared files.  Please see attached zip entitled FAGTOPZAccessControl.zip
