### ISSUE TITLE
A user should not be able to access private ‘sandboxes’ of data (e.g. My Sequences) without proper permissions.

### ISSUE THREAD

**Issue by mfero** [TeselaGen/das#135]
A user should not be able to access private ‘sandboxes’ of data (e.g. My Sequences) unless they have the “editor” or “admin” role (DAS#26).

This seems to be the way things are working. But not sure why a viewer would not be able to see data in shared repo using VE. A ticket has been created to this effect.

**Comment by njhillson** [comment]
Ok, so does look like viewer only roles should not have their own my sequences. This is what I am seeing. Passing...
