### ISSUE TITLE
Usernames (regardless of case) should be unique in the app (DAS#27)

### ISSUE THREAD

**Issue by mfero** [TeselaGen/das#137]
"Usernames (regardless of case) should be unique in the app, creating a user account should throw an error if a duplicate name is entered.
This was demonstrated multiple times the week of November 2 when both upper case and lower case versions of the same DOWID were being created in Peony."

**Comment by mfero** [comment]
Created user CaMeLcAsE... from the administrative panel... app prevented me from creating a 2nd user named cAmElCaSe, and popped up a toaster warning message. looks good.

**Comment by njhillson** [comment]
Looks like it is now looking for a case-insensitive match for username before new account creation.

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/ve#1740
