### ISSUE TITLE
A user cannot access the following API routes unless they have the “user manager” or “admin” role (DAS#28)

### ISSUE THREAD

**Issue by mfero** [TeselaGen/das#140]
"A user cannot access the following API routes unless they have the “user manager” or “admin” role
get('/GetPeonyUsers/:username')
get('/GetPeonyUsers/:username/:targetAccount') get('/GetPeonyUserRoles/:username')
get('/GetPeonyUserRoles/:username/:targetAccount')
get('/GetPeonyRoles/:username')
get('/GetPeonyUserAttributes')
get('/admin/sequences/:user_id')
get(‘/activityLog’)"

**Comment by mfero** [comment]
This has been fixed. Requires QA.

**Comment by mfero** [comment]
I created a new user with view, edit roles.  When I logged in I could not access the above routes through the "admin" panel because it was grayed out. Maybe we should just not have it appear at all, since graying out usually signifies that something is accessible to the current user under the right conditions.

**Comment by njhillson** [comment]
Hard to test directly; agree with Mike that would be better not to display "Admin Panel" option at all to non-admins...
