### ISSUE TITLE
Amino acid sequences were not successfully loaded. (DAS#10)

### ISSUE THREAD

**Issue by mfero** [TeselaGen/das#142]
Related to teselagen/das#122

**Comment by mfero** [comment]
Seems like I can upload both fasta and genbank protein data files.

**Comment by njhillson** [comment]
I was not able to load GenPept files. Failing.

**Comment by mfero** [comment]
Note: the new ticket we will use for further enhancing and debugging the parsers is TeselaGen/ve#1597
