### ISSUE TITLE
Create new user validation(DAS#5)

### ISSUE THREAD

**Issue by mfero** [TeselaGen/das#158]
Admin Panel > User Management > Create New User - Do we need validation for the different fields?

**Comment by mfero** [comment]
How is this being handled in connection wth Big Bird?

**Comment by mcfa77y** [comment]
looks like the only required fields at the moment are username and email
![screen shot 2015-11-30 at 3 27 53 pm](https://cloud.githubusercontent.com/assets/1772137/11487853/0266614a-9777-11e5-89e2-eda1b523ddbf.png)

**Comment by mcfa77y** [comment]
connects TeselaGen/das#137

**Comment by mfero** [comment]
Testing from the administration page... creating a new user... validation is working as I would expect it to. moving along.

**Comment by njhillson** [comment]
Seems to look ok.

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/ve#1738
