### ISSUE TITLE
format login user roles

### ISSUE THREAD

**Issue by mcfa77y** [TeselaGen/das#170]
There was a difficult-to-reproduce bug appearing in the app where the logged in user would lose their roles, resulting in funny behavior like the admin panel disappearing from the username dropdown menu.  

Joe and I are pretty sure this was happening because the /login route did not return the user roles in a format the front-end expects, and this pull request addresses that problem.

**Comment by mfero** [comment]
since there is no info on how to generate original issue, I'll move along.

**Comment by mcfa77y** [comment]
@mfero, steps to reproduce
1) login with user that has admin prilages
2) check that admin panel is accessible from dropdown in the upper right corner

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/ve#1737
