### ISSUE TITLE
Shared part and sequences - not able to preview or open in VE

### ISSUE THREAD

**Issue by craftjk** [TeselaGen/das#20]
_From @njhillson on October 31, 2015 16:13_

I don't seem to be able to single click preview or double click open shared parts or sequences.

_Copied from original issue: TeselaGen/ve#1537_

**Comment by craftjk** [comment]
_From @mfero on October 31, 2015 18:12_

This is covered by #1429

**Comment by mfero** [comment]
working.

**Comment by njhillson** [comment]
Failing. Can not double click on shared part in part library to open in VE.

**Comment by mfero** [comment]
As far as I can tell, this is the same ticket at teselagen/das#23
