### ISSUE TITLE
Can't save AA sequence from text input interface

### ISSUE THREAD

**Issue by craftjk** [TeselaGen/das#21]
_From @mfero on October 31, 2015 2:46_

Can't save AA sequence from text input interface.
![screen shot 2015-10-30 at 7 44 52 pm](https://cloud.githubusercontent.com/assets/7561861/10861512/16acded6-7f3f-11e5-924b-1da8ac1e06ce.png)

_Copied from original issue: TeselaGen/ve#1534_

**Comment by mfero** [comment]
Not exactly related to database migration, but we may as well fix this now and not have it linger.

**Comment by mfero** [comment]
Seems to be working. the feature that removes non-AA characters is nice. I did not check it for accuracy against the standard set of AA characters.

**Comment by njhillson** [comment]
This works for all 20 naturally occurring amino acids.
