### ISSUE TITLE
Authentication Page Links and Functions

### ISSUE THREAD

**Issue by craftjk** [TeselaGen/das#39]
_From @mfero on October 17, 2015 19:52_

Check all links and functions on Login page. Many are missing.
1) Active Directory Login
2) Registration Request
3) Forgot Password
4) External links need to be made internal
5) Local Login is working nicely... However "Check Email" notification pops up when a successful login has been achieved.... this may be because no valid email yet exists. Presumably this will get fixed with 1) above.

_Copied from original issue: TeselaGen/ve#1427_

**Comment by craftjk** [comment]
_From @rpavez on October 20, 2015 11:28_

1) This should be working now m please check again with username mike@ldap.teselagen and password Te#rocks (Selecting LDAP authentication in Connection Type) A bug I detected is just after login in a message shows Welcome "undefined", should be an easy fix.
2) Registration is planned to be implemented only "Admin" users, please correct me if I'm wrong with this.
3) This may be useful for "local users" but its very low priority since most of DOW users will not require this because they will just use their Active Directory credentials.
4) The right side of the login window its just an static HTML, please send which links keep/remove and which text is appropriate there.

**Comment by craftjk** [comment]
_From @mfero on October 28, 2015 22:22_

Has this been pushed? I don't see any change.

![image](https://cloud.githubusercontent.com/assets/7561861/10804982/ba731562-7d87-11e5-85e2-cfbdcf696cf1.png)

**Comment by rpavez** [comment]
Test with mike@ldap.teselagen.com instead of mike@ldap.teselagen ... missing the .com also remember to use Connection Type LDAP.

**Comment by rpavez** [comment]
Can we close this ticket and create a new one just for LDAP? We need to standarize LDAP to either uppercase or lower case, and check it works for Dow. One test would be create an LDAP user like rpavez@ldap.teselagen and RPAVEZ@ldap.teselagen.com and make suer only one user is created.

**Comment by mfero** [comment]
Sure. I think it should be tagged as DAS 90-day.
