### ISSUE TITLE
Logo above 'Authenticating to server' is cut off

### ISSUE THREAD

**Issue by craftjk** [TeselaGen/das#65]
_From @craftjk on September 26, 2015 2:15_

![screen shot 2015-09-25 at 7 14 16 pm](https://cloud.githubusercontent.com/assets/4167907/10115374/b1fd950c-63b9-11e5-9d81-b5d8f55d47dd.png)

_Copied from original issue: TeselaGen/ve#1406_

**Comment by mfero** [comment]
Not fixed.  just after authentication, an image of 1/2 of the DAS log appears.

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/ve#1744
