### ISSUE TITLE
Part library - date created and modified fields not updated

### ISSUE THREAD

**Issue by craftjk** [TeselaGen/das#86]
_From @njhillson on October 31, 2015 16:24_

Upon part creation, the date modified and created fields aren't getting set.

_Copied from original issue: TeselaGen/ve#1539_

**Comment by mfero** [comment]
They appear to be getting set now in "Sequences" library, but there is nothing appearing in the "Parts" library under "date created" and "date modified"

**Comment by mfero** [comment]
something is wrong with the indexing of this card, it appears twice in waffle. I'm going to declare victory on this ticket and close it to clean up the board.

**Comment by rpavez** [comment]
Yeah, I was trying to move some tickets and create a new issue in Waffle this morning and was getting lot of errors.

**Comment by njhillson** [comment]
Looks better.
