### ISSUE TITLE
Access control not changing access

### ISSUE THREAD

**Issue by craftjk** [TeselaGen/das#87]
_From @mfero on October 30, 2015 16:6_

After changing access to false for sequences in repo... those sequences still show up in the shared repo.

_Copied from original issue: TeselaGen/ve#1525_

**Comment by craftjk** [comment]
_From @mfero on October 31, 2015 4:4_

I don't see sequences appear/disappear from "Peony Sequence Repo" for user "mikeeee" when I change access to all of the shared sequences when acting as admin in account "mikefero".  I think the desired behavior is:

Administrator:
Admin Panel > Access Control > Search for "mikeeee"
Double-Click on "mikeeee" row and bring up the "Modify..." window.
Change access from false to true for some sequence.

User "mikeeee" should immediately be able to see that sequence in his "Peony Sequence Repo" view.

**Comment by mfero** [comment]
working in context of other fixes.

**Comment by njhillson** [comment]
Looks like this is working
