### ISSUE TITLE
Admin: No way to inactivate user

### ISSUE THREAD

**Issue by craftjk** [TeselaGen/das#88]
_From @mfero on October 30, 2015 15:55_

I could not see a way to inactivate or delete a user.

_Copied from original issue: TeselaGen/ve#1524_

**Comment by craftjk** [comment]
_From @mfero on October 31, 2015 2:32_

Interface for deleting (but not inactivating) user now exists (via context menu) but I don't see anything change in the listing of the user in the interface that indicates to me that the user is now inactivated or deleted.

**Comment by craftjk** [comment]
_From @njhillson on October 31, 2015 16:38_

I received an error when trying to delete a user via the right click context menu.

**Comment by mfero** [comment]
Working, but activate checkbox is not preserving "active" state once a user is activated.

**Comment by mfero** [comment]
The activate function is currently done in the right-click menu and the activate checkboxes have been removed. This is an ok temporary fix. Moving forward:

1. Remove context menu.
2. All context menu functions should all be handled from a single unified administrative panel that comes up upon double-clicking a user.
