### ISSUE TITLE
Give admins ability to delete seqs and parts from shared repo

### ISSUE THREAD

**Issue by craftjk** [TeselaGen/das#92]
_From @craftjk on October 29, 2015 20:41_

Give admins ability to delete seqs and parts from shared repo

_Copied from original issue: TeselaGen/ve#1512_

**Comment by craftjk** [comment]
_From @mfero on October 30, 2015 1:53_

Can't test without having admin privileges.

**Comment by craftjk** [comment]
@mfero You, Nathan, and the dev team all have admin privileges now

**Comment by craftjk** [comment]
_From @njhillson on October 31, 2015 16:1_

I can't see how it is possible to delete parts from the shared repo. From right click context only make a copy and export are available options. Also, right click context does not work in shared part library when multiple rows are selected.

Was not able to delete a sequence from the shared sequence library. Just got spinning wheel and had to refresh page. Was not able to test multiple sequence selection functionality as was not able to add more sequences to the shared sequence library.

 Failing.

**Comment by mfero** [comment]
Seems like the dangerous act of deleting repo sequences is working. Hope they backup their database.

**Comment by njhillson** [comment]
Looks like this is working.

**Comment by njhillson** [comment]
This ticket should clarified. It is not possible (nor intended) for admins to delete parts directly from the shared part library. The only way to do this is to delete the shared sequence that contains the shared parts. Going to pass for now, but the ticket needs to be clarified.
